const DB_NAME='louvor-em-acao', DB_VERSION=1;
const state={tracks:[],recordings:[],queue:[],queueIndex:-1,category:'Todas',shuffle:false,repeat:false,timer:null,recording:null,recordChunks:[],deferredInstall:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const supported=['audio/mpeg','audio/mp4','audio/aac','audio/wav','audio/ogg'];

function db(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains('tracks'))d.createObjectStore('tracks',{keyPath:'id'});if(!d.objectStoreNames.contains('recordings'))d.createObjectStore('recordings',{keyPath:'id'});if(!d.objectStoreNames.contains('settings'))d.createObjectStore('settings',{keyPath:'key'});};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function store(name,value){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(name,'readwrite').objectStore(name).put(value);r.onsuccess=res;r.onerror=()=>rej(r.error);});}
async function remove(name,id){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(name,'readwrite').objectStore(name).delete(id);r.onsuccess=res;r.onerror=()=>rej(r.error);});}
async function all(name){const d=await db();return new Promise((res,rej)=>{const r=d.transaction(name).objectStore(name).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function getSetting(key){const d=await db();return new Promise((res,rej)=>{const r=d.transaction('settings').objectStore('settings').get(key);r.onsuccess=()=>res(r.result?.value);r.onerror=()=>rej(r.error);});}
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),3000);}
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function duration(s){if(!Number.isFinite(s))return'0:00';return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;}
function trackMatches(t){return state.category==='Todas'||(t.categories||[]).includes(state.category)||(state.category==='Favoritas'&&t.favorite);}
function tracksForView(){return state.tracks.filter(trackMatches);}
function categories(){return ['Todas','Favoritas',...new Set(state.tracks.flatMap(t=>t.categories||[]))];}

function render(){renderLibrary();renderPlayer();renderLyrics();renderRecordings();updateStorage();}
function renderLibrary(){const list=$('#trackList'), filtered=tracksForView();$('#trackCount').textContent=`${filtered.length} música${filtered.length===1?'':'s'}`;$('#categoryRow').innerHTML=categories().map(c=>`<button class="${c===state.category?'active':''}" data-category="${esc(c)}">${esc(c)}</button>`).join('');list.innerHTML=filtered.length?filtered.map(trackCard).join(''):'<div class="empty">Sua Biblioteca está vazia. Toque em “Adicionar músicas” para começar.</div>';$$('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;renderLibrary();});bindTrackActions(list);}
function trackCard(t){return `<article class="track"><div class="track-cover">♫</div><div class="track-info"><div class="track-title">${esc(t.title)}</div><div class="track-meta">${esc(t.artist||'Artista não informado')}${t.categories?.length?` · ${esc(t.categories.join(', '))}`:''}</div></div><div class="track-actions"><button data-play="${t.id}" title="Tocar">▶</button><button data-edit="${t.id}" title="Editar">✎</button><button data-fav="${t.id}" title="Favorita">${t.favorite?'★':'☆'}</button></div></article>`;}
function bindTrackActions(root){root.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>startQueue([findTrack(b.dataset.play)]));root.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openTrack(findTrack(b.dataset.edit)));root.querySelectorAll('[data-fav]').forEach(b=>b.onclick=async()=>{const t=findTrack(b.dataset.fav);t.favorite=!t.favorite;await store('tracks',t);render();});}
function findTrack(id){return state.tracks.find(t=>t.id===id);}

function renderPlayer(){const active=state.queue[state.queueIndex];$('#queueCount').textContent=`${state.queue.length} na fila`;$('#queueList').innerHTML=state.queue.length?state.queue.map((t,i)=>`<article class="track"><div class="track-cover">${i===state.queueIndex?'♫':'·'}</div><div class="track-info"><div class="track-title">${esc(t.title)}</div><div class="track-meta">${esc(t.artist||'')}</div></div><div class="track-actions"><button data-queue-index="${i}">Tocar</button></div></article>`).join(''):'<div class="empty">Escolha músicas na Biblioteca para criar uma fila.</div>';$$('[data-queue-index]').forEach(b=>b.onclick=()=>playIndex(Number(b.dataset.queueIndex)));$('#shuffleButton').setAttribute('aria-pressed',String(state.shuffle));$('#repeatButton').setAttribute('aria-pressed',String(state.repeat));if(!active)return;$('#nowTitle').textContent=active.title;$('#nowArtist').textContent=active.artist||'Artista não informado';$('#nowCategory').textContent=active.categories?.join(' · ')||'Biblioteca';}
function renderLyrics(){const target=$('#lyricsList'),withText=state.tracks.filter(t=>t.lyrics||t.chords||t.chordAsset);target.innerHTML=withText.length?withText.map(t=>`<article class="track"><div class="track-cover">♬</div><div class="track-info"><div class="track-title">${esc(t.title)}</div><div class="track-meta">${t.lyrics?'Letra ':''}${t.chords?'· Cifra ':''}${t.chordAsset?'· Arquivo de cifra':''}</div></div><div class="track-actions"><button data-edit="${t.id}">Abrir</button></div></article>`).join(''):'<div class="empty">Ainda não há letras ou cifras. Abra uma música e toque em editar para adicionar.</div>';bindTrackActions(target);}
function renderRecordings(){const target=$('#recordingsList');target.innerHTML=state.recordings.length?state.recordings.map(r=>`<article class="track"><div class="track-cover">●</div><div class="track-info"><div class="track-title">${esc(r.title)}</div><div class="track-meta">${new Date(r.createdAt).toLocaleString('pt-BR')}</div></div><div class="track-actions"><button data-record-play="${r.id}">▶</button><button data-record-delete="${r.id}">Excluir</button></div></article>`).join(''):'<div class="empty">Nenhuma gravação ainda.</div>';$$('[data-record-play]').forEach(b=>b.onclick=()=>{const r=state.recordings.find(x=>x.id===b.dataset.recordPlay);new Audio(URL.createObjectURL(r.blob)).play();});$$('[data-record-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir esta gravação?'))return;await remove('recordings',b.dataset.recordDelete);await load();toast('Gravação excluída.');});}

async function importTracks(files){let added=0;for(const file of files){const probe=document.createElement('audio');const likely=supported.includes(file.type)||/\.(mp3|m4a|aac|wav|ogg)$/i.test(file.name);if(!likely){toast(`${file.name}: formato não aceito.`);continue;}const title=file.name.replace(/\.[^.]+$/,'');await store('tracks',{id:uid(),title,artist:'',categories:[],note:'',lyrics:'',chords:'',favorite:false,file,createdAt:Date.now()});added++;}await load();toast(`${added} música${added===1?' adicionada':'s adicionadas'} à Biblioteca.`);}
function startQueue(tracks){state.queue=tracks.filter(Boolean);state.queueIndex=0;playIndex(0);}
function playIndex(index){if(!state.queue.length)return;state.queueIndex=(index+state.queue.length)%state.queue.length;const t=state.queue[state.queueIndex],audio=$('#audioPlayer');if(audio.dataset.url)URL.revokeObjectURL(audio.dataset.url);const url=URL.createObjectURL(t.file);audio.dataset.url=url;audio.src=url;audio.play().then(()=>{$('#playButton').textContent='❚❚';renderPlayer();}).catch(()=>toast('Toque em ▶ para permitir a reprodução.'));renderPlayer();}
function next(){if(!state.queue.length)return;if(state.shuffle&&state.queue.length>1){let n;do n=Math.floor(Math.random()*state.queue.length);while(n===state.queueIndex);return playIndex(n);}if(state.queueIndex<state.queue.length-1)return playIndex(state.queueIndex+1);if(state.repeat)return playIndex(0);$('#audioPlayer').pause();$('#playButton').textContent='▶';}
function previous(){if(state.queue.length)playIndex(Math.max(0,state.queueIndex-1));}

function openTrack(t){if(!t)return;$('#editTrackId').value=t.id;$('#editTitle').value=t.title;$('#editArtist').value=t.artist||'';$('#editCategories').value=(t.categories||[]).join(', ');$('#editNote').value=t.note||'';$('#editLyrics').value=t.lyrics||'';$('#editChords').value=t.chords||'';$('#chordAsset').value='';$('#trackDialog').showModal();}
async function saveTrack(){const t=findTrack($('#editTrackId').value);if(!t)return;t.title=$('#editTitle').value.trim();t.artist=$('#editArtist').value.trim();t.categories=$('#editCategories').value.split(',').map(x=>x.trim()).filter(Boolean);t.note=$('#editNote').value.trim();t.lyrics=$('#editLyrics').value;t.chords=$('#editChords').value;const asset=$('#chordAsset').files[0];if(asset)t.chordAsset={name:asset.name,type:asset.type,file:asset};await store('tracks',t);await load();toast('Música atualizada.');}

function setTimer(minutes){clearTimer();const end=Date.now()+minutes*60000;state.timer=setInterval(()=>{const remain=Math.max(0,end-Date.now());$('#timerStatus').textContent=`A música para em ${Math.ceil(remain/60000)} min.`;if(!remain){$('#audioPlayer').pause();$('#playButton').textContent='▶';clearTimer();toast('Temporizador concluído.');}},1000);$('#timerStatus').textContent=`A música para em ${minutes} min.`;}
function clearTimer(){if(state.timer)clearInterval(state.timer);state.timer=null;$('#timerStatus').textContent='Sem temporizador.';}
async function record(){if(state.recording?.state==='recording'){state.recording.stop();return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});state.recordChunks=[];const rec=new MediaRecorder(stream);state.recording=rec;rec.ondataavailable=e=>state.recordChunks.push(e.data);rec.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(state.recordChunks,{type:rec.mimeType});await store('recordings',{id:uid(),title:`Gravação ${new Date().toLocaleDateString('pt-BR')}`,blob,createdAt:Date.now()});state.recording=null;$('#recordButton').textContent='● Começar gravação';$('#recordingStatus').textContent='Gravação salva.';await load();};rec.start();$('#recordButton').textContent='■ Parar gravação';$('#recordingStatus').textContent='Gravando…';}catch{toast('Não foi possível usar o microfone. Verifique a permissão.');}}
async function blobData(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob);});}
function dataBlob(data){const [head,body]=data.split(',');const type=(head.match(/data:(.*?);base64/)||[])[1]||'application/octet-stream';const bytes=Uint8Array.from(atob(body),c=>c.charCodeAt(0));return new Blob([bytes],{type});}
async function exportBackup(){try{toast('Preparando backup completo…');const tracks=await Promise.all(state.tracks.map(async({file,chordAsset,...t})=>({...t,file:file?{name:file.name,type:file.type,data:await blobData(file)}:null,chordAsset:chordAsset?{name:chordAsset.name,type:chordAsset.type,data:await blobData(chordAsset.file)}:null})));const recordings=await Promise.all(state.recordings.map(async({blob,...r})=>({...r,blob:{type:blob.type,data:await blobData(blob)}})));const data={version:1,createdAt:new Date().toISOString(),tracks,recordings};const blob=new Blob([JSON.stringify(data)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`louvor-em-acao-backup-completo-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Backup completo criado. Guarde-o em local seguro.');}catch{toast('Não foi possível criar o backup. Tente com menos músicas por vez.');}}
async function restoreBackup(file){try{const backup=JSON.parse(await file.text());if(!Array.isArray(backup.tracks)||!Array.isArray(backup.recordings))throw Error();for(const item of backup.tracks){const {file:audio,chordAsset,...t}=item;await store('tracks',{...t,id:uid(),file:audio?new File([dataBlob(audio.data)],audio.name,{type:audio.type}):null,chordAsset:chordAsset?{name:chordAsset.name,type:chordAsset.type,file:new File([dataBlob(chordAsset.data)],chordAsset.name,{type:chordAsset.type})}:null});}for(const item of backup.recordings){const {blob,...r}=item;await store('recordings',{...r,id:uid(),blob:dataBlob(blob.data)});}await load();toast('Backup restaurado com músicas e gravações.');}catch{toast('Este arquivo de backup não é válido.');}}
async function updateStorage(){if(navigator.storage?.estimate){const e=await navigator.storage.estimate();$('#storageStatus').textContent=`Usando cerca de ${(e.usage/1024/1024||0).toFixed(1)} MB neste aparelho.`;}}
async function load(){state.tracks=await all('tracks');state.recordings=await all('recordings');render();}
function setup(){
  $$('[data-nav]').forEach(b=>b.onclick=()=>{const id=b.dataset.nav;$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${id}`));$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));window.scrollTo({top:0,behavior:'smooth'});});
  $('#audioPicker').onchange=e=>importTracks([...e.target.files]);$('#audioPlayer').onended=next;$('#audioPlayer').ontimeupdate=()=>{const a=$('#audioPlayer');$('#progress').value=a.duration?100*a.currentTime/a.duration:0;$('#elapsed').textContent=duration(a.currentTime);$('#duration').textContent=duration(a.duration);};$('#progress').oninput=e=>{const a=$('#audioPlayer');if(a.duration)a.currentTime=a.duration*e.target.value/100;};
  $('#playButton').onclick=()=>{const a=$('#audioPlayer');if(!state.queue.length)return toast('Escolha músicas na Biblioteca.');if(!a.src)return playIndex(0);a.paused?a.play().then(()=>$('#playButton').textContent='❚❚'):a.pause();if(!a.paused)$('#playButton').textContent='❚❚';else $('#playButton').textContent='▶';};$('#nextButton').onclick=next;$('#previousButton').onclick=previous;$('#shuffleButton').onclick=()=>{state.shuffle=!state.shuffle;renderPlayer();};$('#repeatButton').onclick=()=>{state.repeat=!state.repeat;renderPlayer();};$('#clearQueue').onclick=()=>{state.queue=[];state.queueIndex=-1;$('#audioPlayer').pause();$('#audioPlayer').src='';renderPlayer();};
  $$('[data-timer]').forEach(b=>b.onclick=()=>setTimer(Number(b.dataset.timer)));$('#setCustomTimer').onclick=()=>{const n=Number($('#customMinutes').value);if(n>0)setTimer(n);else toast('Digite uma quantidade de minutos.');};$('#stopTimer').onclick=clearTimer;$('#recordButton').onclick=record;
  $('#trackForm').addEventListener('submit',e=>{if(e.submitter?.id==='saveTrack')saveTrack();});$('#exportBackup').onclick=exportBackup;$('#restorePicker').onchange=e=>e.target.files[0]&&restoreBackup(e.target.files[0]);
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;$('#installButton').classList.remove('hidden');});$('#installButton').onclick=async()=>{if(state.deferredInstall){state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;$('#installButton').classList.add('hidden');}};
  if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');load();
}
setup();
